name: codspeed-benchmarks

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install -r tests/requirements.in
    - run: make
    - uses: CodSpeedHQ/action@v2
      with:
        token: ${{ secrets.CODSPEED_TOKEN }}
        run: python -m pytest --codspeed
